const DbScreen4b = [
    {
      id: "1",
      titleProduct: "Intel Core i5 14400",
      nameShop: "Intel",
      imagePreview: "ImageProductPreview.png",
      priceProduct: "5.199.000",
      reviewProduct: 3,
      rating: 0,
    },
    {
      id: "2",
      titleProduct: "Intel Core i5 14600K",
      nameShop: "Intel",
      imagePreview: "ImageProductPreview.png",
      priceProduct: "9.590.000",
      reviewProduct: 3,
      rating: 0,
    },
    {
      id: "3",
      titleProduct: "Intel Core i7 14700",
      nameShop: "Intel",
      imagePreview: "ImageProductPreview.png",
      priceProduct: "12.590.000",
      reviewProduct: 3,
      rating: 1,
    },
    {
      id: "4",
      titleProduct: "Intel Core i7 14700K",
      nameShop: "Intel",
      imagePreview: "ImageProductPreview.png",
      priceProduct: "15.900.000",
      reviewProduct: 3,
      rating: 1,
    },
    {
      id: "5",
      titleProduct: "Intel Core i7 14900",
      nameShop: "Intel",
      imagePreview: "ImageProductPreview.png",
      priceProduct: "16.900.000",
      reviewProduct: 3,
      rating: 3,
    },
    {
      id: "6",
      titleProduct: "Intel Core i7 14900K",
      nameShop: "Intel",
      imagePreview: "ImageProductPreview.png",
      priceProduct: "20.900.000",
      reviewProduct: 3,
      rating: 2,
    },
    {
      id: "7",
      titleProduct: "Mainboard Asus Prime H710M",
      nameShop: "Asus",
      imagePreview: "ImageProductPreview.png",
      priceProduct: "3.299.000",
      reviewProduct: 3,
      rating: 1,
    },
    {
      id: "8",
      titleProduct: "Mainboard MSI Motar B760M",
      nameShop: "Msi",
      imagePreview: "ImageProductPreview.png",
      priceProduct: "5.599.000",
      reviewProduct: 3,
      rating: 4,
    },
    {
      id: "9",
      titleProduct: "Mainboard Aorus Pro Z790",
      nameShop: "Gigabyte",
      imagePreview: "ImageProductPreview.png",
      priceProduct: "9.990.000",
      reviewProduct: 3,
      rating: 4,
    },
    {
      id: "10",
      titleProduct: "SSD 990 Pro 2TB Gen 4x4 PCIE",
      nameShop: "Samsung",
      imagePreview: "ImageProductPreview.png",
      priceProduct: "4.790.000",
      reviewProduct: 3,
      rating: 2,
    },
    {
      id: "11",
      titleProduct: "Intel Core I3 12100F",
      nameShop: "Intel",
      imagePreview: "ImageProductPreview.png",
      priceProduct: "2.499.000",
      reviewProduct: 3,
      rating: 5,
    },
    {
      id: "12",
      titleProduct: "Intel Core I3 12400F",
      nameShop: "Intel",
      imagePreview: "ImageProductPreview.png",
      priceProduct: "4.399.000",
      reviewProduct: 3,
      rating: 1,
    },
  ];

  export default DbScreen4b